"""initial_schema_complete

Revision ID: 8acb2927bf44
Revises: 
Create Date: 2025-12-31 16:22:55.303305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8acb2927bf44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # ========================================================================
    # STEP 1: CREATE PostgreSQL Extension
    # ========================================================================
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    
    # ========================================================================
    # STEP 2: CREATE PostgreSQL Function for updated_at
    # ========================================================================
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # ========================================================================
    # STEP 3: CREATE TABLES (auto-generated by Alembic)
    # ========================================================================
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('source_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('TOAST', 'DOORDASH', 'SQUARE', name='ordersourceenum'), nullable=False),
    sa.Column('source_order_id', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('DINE_IN', 'TAKEOUT', 'DELIVERY', 'PICKUP', name='ordertypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='orderstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('service_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('server_name', sa.String(length=255), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('contains_alcohol', sa.Boolean(), nullable=True),
    sa.Column('is_catering', sa.Boolean(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_order_id', name='uq_order_source')
    )
    op.create_index('idx_orders_business_date', 'orders', ['business_date'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_location_date', 'orders', ['location_id', 'business_date'], unique=False)
    op.create_index('idx_orders_location_date_status', 'orders', ['location_id', 'business_date', 'status'], unique=False)
    op.create_index('idx_orders_location_id', 'orders', ['location_id'], unique=False)
    op.create_index('idx_orders_order_type', 'orders', ['order_type'], unique=False)
    op.create_index('idx_orders_source', 'orders', ['source'], unique=False)
    op.create_index('idx_orders_source_created', 'orders', ['source', 'created_at'], unique=False)
    op.create_index('idx_orders_source_order_id', 'orders', ['source', 'source_order_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_address_line1', sa.String(length=255), nullable=True),
    sa.Column('delivery_address_line2', sa.String(length=255), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_state', sa.String(length=50), nullable=True),
    sa.Column('delivery_zip_code', sa.String(length=20), nullable=True),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('dasher_name', sa.String(length=255), nullable=True),
    sa.Column('dasher_id', sa.String(length=255), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dasher_tip', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_delivery_orders_delivery_time', 'delivery_orders', ['delivery_time'], unique=False)
    op.create_index('idx_delivery_orders_order_id', 'delivery_orders', ['order_id'], unique=False)
    op.create_index('idx_delivery_orders_pickup_time', 'delivery_orders', ['pickup_time'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('source_item_id', sa.String(length=255), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_items_category_name', 'order_items', ['category_name'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_order_product', 'order_items', ['order_id', 'product_id'], unique=False)
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_items_source_metadata', 'order_items', ['source_metadata'], unique=False, postgresql_using='gin')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('TOAST', 'DOORDASH', 'SQUARE', name='ordersourceenum'), nullable=False),
    sa.Column('source_payment_id', sa.String(length=255), nullable=True),
    sa.Column('payment_type', sa.Enum('CARD', 'CASH', 'DIGITAL_WALLET', 'OTHER', name='paymenttypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatusenum'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_entry_method', sa.String(length=50), nullable=True),
    sa.Column('wallet_brand', sa.String(length=50), nullable=True),
    sa.Column('cash_tendered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refund_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_payment_id', name='uq_payment_source')
    )
    op.create_index('idx_payments_card_brand', 'payments', ['card_brand'], unique=False)
    op.create_index('idx_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('idx_payments_payment_type', 'payments', ['payment_type'], unique=False)
    op.create_index('idx_payments_processed_at', 'payments', ['processed_at'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_table('product_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('TOAST', 'DOORDASH', 'SQUARE', name='ordersourceenum'), nullable=False),
    sa.Column('source_product_id', sa.String(length=255), nullable=False),
    sa.Column('source_product_name', sa.String(length=255), nullable=False),
    sa.Column('source_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_manual_match', sa.Boolean(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_product_id', name='uq_product_mapping_source')
    )
    op.create_index('idx_product_mappings_product_id', 'product_mappings', ['product_id'], unique=False)
    op.create_index('idx_product_mappings_source', 'product_mappings', ['source', 'source_product_id'], unique=False)
    op.create_table('toast_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_check_id', sa.String(length=255), nullable=False),
    sa.Column('check_number', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('server_name', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_check_id', name='uq_toast_check_source')
    )
    op.create_index('idx_toast_checks_closed_at', 'toast_checks', ['closed_at'], unique=False)
    op.create_index('idx_toast_checks_opened_at', 'toast_checks', ['opened_at'], unique=False)
    op.create_index('idx_toast_checks_order_id', 'toast_checks', ['order_id'], unique=False)
    op.create_table('order_item_modifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('modifier_name', sa.String(length=255), nullable=False),
    sa.Column('modifier_value', sa.String(length=255), nullable=True),
    sa.Column('price_adjustment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('source_modifier_id', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_item_modifiers_order_item_id', 'order_item_modifiers', ['order_item_id'], unique=False)
    # ### end Alembic commands ###
    
    # ========================================================================
    # STEP 4: CREATE TRIGGERS for updated_at columns
    # ========================================================================
    op.execute("""
        CREATE TRIGGER update_locations_updated_at
            BEFORE UPDATE ON locations
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_categories_updated_at
            BEFORE UPDATE ON categories
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_products_updated_at
            BEFORE UPDATE ON products
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_product_mappings_updated_at
            BEFORE UPDATE ON product_mappings
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_orders_updated_at
            BEFORE UPDATE ON orders
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_order_items_updated_at
            BEFORE UPDATE ON order_items
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_payments_updated_at
            BEFORE UPDATE ON payments
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_delivery_orders_updated_at
            BEFORE UPDATE ON delivery_orders
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        
        CREATE TRIGGER update_toast_checks_updated_at
            BEFORE UPDATE ON toast_checks
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
    """)
    
    # ========================================================================
    # STEP 5: CREATE ADDITIONAL INDEXES (trigram for text search)
    # ========================================================================
    op.create_index(
        'idx_products_name_trgm',
        'products',
        ['name'],
        postgresql_using='gin',
        postgresql_ops={'name': 'gin_trgm_ops'}
    )
    op.create_index('idx_products_normalized_name', 'products', ['normalized_name'])
    op.create_index('idx_categories_normalized_name', 'categories', ['normalized_name'])


def downgrade() -> None:
    """Downgrade schema."""
    
    # ========================================================================
    # STEP 1: DROP ADDITIONAL INDEXES
    # ========================================================================
    op.drop_index('idx_categories_normalized_name', table_name='categories')
    op.drop_index('idx_products_normalized_name', table_name='products')
    op.drop_index('idx_products_name_trgm', table_name='products', postgresql_using='gin')
    
    # ========================================================================
    # STEP 2: DROP TRIGGERS
    # ========================================================================
    op.execute("""
        DROP TRIGGER IF EXISTS update_toast_checks_updated_at ON toast_checks;
        DROP TRIGGER IF EXISTS update_delivery_orders_updated_at ON delivery_orders;
        DROP TRIGGER IF EXISTS update_payments_updated_at ON payments;
        DROP TRIGGER IF EXISTS update_order_items_updated_at ON order_items;
        DROP TRIGGER IF EXISTS update_orders_updated_at ON orders;
        DROP TRIGGER IF EXISTS update_product_mappings_updated_at ON product_mappings;
        DROP TRIGGER IF EXISTS update_products_updated_at ON products;
        DROP TRIGGER IF EXISTS update_categories_updated_at ON categories;
        DROP TRIGGER IF EXISTS update_locations_updated_at ON locations;
    """)
    
    # ========================================================================
    # STEP 3: DROP TABLES (auto-generated by Alembic)
    # ========================================================================
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_item_modifiers_order_item_id', table_name='order_item_modifiers')
    op.drop_table('order_item_modifiers')
    op.drop_index('idx_toast_checks_order_id', table_name='toast_checks')
    op.drop_index('idx_toast_checks_opened_at', table_name='toast_checks')
    op.drop_index('idx_toast_checks_closed_at', table_name='toast_checks')
    op.drop_table('toast_checks')
    op.drop_index('idx_product_mappings_source', table_name='product_mappings')
    op.drop_index('idx_product_mappings_product_id', table_name='product_mappings')
    op.drop_table('product_mappings')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_processed_at', table_name='payments')
    op.drop_index('idx_payments_payment_type', table_name='payments')
    op.drop_index('idx_payments_order_id', table_name='payments')
    op.drop_index('idx_payments_card_brand', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_order_items_source_metadata', table_name='order_items', postgresql_using='gin')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.drop_index('idx_order_items_order_product', table_name='order_items')
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_category_name', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_delivery_orders_pickup_time', table_name='delivery_orders')
    op.drop_index('idx_delivery_orders_order_id', table_name='delivery_orders')
    op.drop_index('idx_delivery_orders_delivery_time', table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_table('products')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_source_order_id', table_name='orders')
    op.drop_index('idx_orders_source_created', table_name='orders')
    op.drop_index('idx_orders_source', table_name='orders')
    op.drop_index('idx_orders_order_type', table_name='orders')
    op.drop_index('idx_orders_location_id', table_name='orders')
    op.drop_index('idx_orders_location_date_status', table_name='orders')
    op.drop_index('idx_orders_location_date', table_name='orders')
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_orders_business_date', table_name='orders')
    op.drop_table('orders')
    op.drop_table('locations')
    op.drop_table('categories')
    # ### end Alembic commands ###
    
    # ========================================================================
    # STEP 4: DROP FUNCTION AND EXTENSION
    # ========================================================================
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
